from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('rti', src, depend = ['PKG_USING_RTI_UART_SAMPLE'], CPPPATH = CPPPATH)

Return('group')
